### ISSUE TITLE
SetText with Date String ?

### ISSUE THREAD

**Issue by amaydiam** [curioustechizen/android-ago#19]
How setText if I have String Date like "2015-08-02 01:01:50" ?

**Comment by curioustechizen** [comment]
@amaydiam Currently, the library expects the date in milliseconds since epoch format - for example, the format returned by `System.currentTimeMillis()`. If you receive the date in String format, you need to first convert it to a `long`. Something along the following lines should work (**Note:- This code is not tested***

```java
//Declare SDF as a static somewhere
static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

//Then, wherever you receive the String date, do this
long dateAsLong = DATE_FROMAT.parse(stringDate).getTime();
relativeTimeTextView.setReferenceTime(dateAsLong);
```
