### ISSUE TITLE
minSdkVersion?

### ISSUE THREAD

**Issue by intrications** [curioustechizen/android-ago#5]
The actual library says android:minSdkVersion="14" but the sample app has android:minSdkVersion="8".

Which is correct?

I'm trying to add Gradle build files and it won't compile without fixing this.

**Comment by marcusforsberg** [comment]
If the library currently does support < 14, any chance that you could change the minSdkVersion to reflect this? This library is crucial for my app but currently the only thing stopping me from supporting < 14. If you don't want to commit to supporting < 14 in the future, you could always put a large notice in the readme. :)

Thanks for your hard work!

**Comment by curioustechizen** [comment]
@marcusforsberg There is a pending PR #14  that sets the minSdk to 11. I hope to merge this in during this week. What minSdk are you targeting?

If this is really urgent, you could clone the repo and set the minSdk yourself as a temporary solution until the official one is published to Maven Central.

Currently the library only requires DateUtils#getRelativeTimeSpanString which is available since API 3. So in theory the minSdk can be set to 3.

**Comment by curioustechizen** [comment]
Set minSdk to 8 with a disclaimer about support for API versions < 11. Fixed in 622747a
