### ISSUE TITLE
Removing the "ago" word 

### ISSUE THREAD

**Issue by abdulmalekDery** [curioustechizen/android-ago#56]
Is there any way to remove the "ago" word from the RelativeTimeTextView?
To be more clear
for example if the RelativeTimeTextView is showing this String 
"16 min. ago"
can I convert it to 
"16 min."
this way is more user friendly ...you know shortest text is always better  
thanks in advance

**Comment by curioustechizen** [comment]
@abdulmalekDery With the current implementation this is not possible. That's because this library does not generate the "16 min ago" string - it just uses Android's `DateUtils` class to get that string. The point of this library is to automatically refresh the text when the time changes.

Also, note that this string will be different depending on the locale.

Having said that, I am willing to explore making the library more flexible such that users have more control over how to display the String. Then, the role of RTTV will be reduced to just auto-refreshing the UI when the time changes, and leaving the exact formatting of the string to the user.

I don't promise anything but I'll look into it.

**Comment by abdulmalekDery** [comment]
@curioustechizen Thank you so much 
but I think we can remove that word "ago" with a simple hack "I wish we could do that"
because this DataUtils return that String "for example the name of that String is s" we could simply call this methods 
if(s.contains(getString(R.string.ago)))
s=s.replace(getString(R.string.ago),"");
I wish this could help

**Comment by curioustechizen** [comment]
@abdulmalekDery Of course, but the point is that the code you shared should be written by the library user. The library should provide a hook for the calling code to customize the text being displayed. It does not make sense to include this code in the library itself.

**Comment by abdulmalekDery** [comment]
@curioustechizen yeah ....I 'm just telling the other users how they could remove that word

**Comment by curioustechizen** [comment]
@abdulmalekDery Great idea. Maybe until I get time to improve the API, I should start a "Recipes" section in the wiki where users who have found such solutions can contribute.

**Comment by curioustechizen** [comment]
@abdulmalekDery v1.4.0 has been released with a new feature that allows you to process the relative time string before it is displayed. This can be used to achieve the behaviour you requested - i.e. trimming certain strings before displaying.

Please try out 1.4.0. I'm closing this issue in the meanwhile.
